/*  Shining Drive JS

    Biography Page
    Goals:
        store the different stories within an array to be called later
    Author: Franco Ramos
    Date:   03/24/2023

    Filename: bio-stories.js
 */

let storyArray = [
    "Starting with the transition between high school and college in 2015, I had always been torn between deciding whether to commit to a hobby in illustration hoping it would someday turn into a career with no plan or sticking to the safe choice in mathematics and getting a stable job. Fearing the unknown I began studying to become an engineering technician.<br><br>I would spend the time in between classes developing illustration skills – being smitten with the chance to one day work with storytelling as a concept artist, I would use all my free time to practice in secret.<br><br>The degree was originally supposed to get me a job in a rookie position and make life become easier in terms of having the freedom to pursue what I really wanted with the financial support to make it happen. I graduated at the top of my class and couldn’t get anything. <br><br>This wasn’t the plan and I had to come up with something to do to support myself. So, I made the decision to transfer into studying to become an engineer as my illustrations weren’t anywhere near ready to go professional with. And in deciding to pursue something more realistic I made the difficult choice to put away all the progress I had made up to that point in illustration.",
    "Transitioning into mechanical engineering was its own type of challenge. In my extended family I’m in the first generation that has attempted to take on higher education and because of that had limited resources whenever there was an obstacle to overcome.<br><br>One of the greatest assets I found in my decision to go with the safe choice was the chance to hang out in the parking lot after class and just share stories with my peers. Being in community college, there’s a fair number of circumstances that might lead someone to try and take on the challenge of trying to turn your life around with a degree, and through sharing we all got to peek a little into some of those circumstances and learn a little from those of us that gained a little wisdom from having more experience than others. <br><br> And while this helped in staying focused on what I was doing, I couldn’t help but think about what I wasn’t doing. The more I kept engineering as my end goal, the more I could see how some of the skills I was picking up through my program might help in picking up a forsaken dream. This is where I started my coding journey, got some jobs that taught me how to appreciate teaching a younger generation through robotics, and kept up some practice in 3D Modeling with Autodesk Inventor.",
    "Finding ways to expand my resources by sharing stories with Professors, it became apparent that I could have a future in academics if I kept working towards it. But as the classes got harder, the motivation got weaker. My original goal was to prove to myself that I could manage an associate degree, which was proven back in 2018. And the goal post then got moved from working towards a bachelor’s, to a possible master’s and beyond in the distance.<br><br>During 2020 in the last semester before I transferred into a bachelor’s degree program, I was able to attend a gathering for undergraduate students considering graduate work, I got to spend an entire day listening to other students who decided to put in 101% into their work and proved that they had a specific twinkle in their eye that let them put in that work. Meanwhile, as my reasons were just beginning to reflect on what I could do for others – their origins have always been about the money. And after listening to other students pour their hearts out through their stories and how that motivated them to make change in the world, I spent the rest of my semester in shame and reflection.<br><br>The pandemic hit and I still didn’t have an answer to how to deal with that shame and thus stalled on bachelor’s program, with my motivation at an all time low. And while time in the world proverbially stood still, I got to spend the days thinking on what to do about my ‘twinkle’. Sneaking in time to do so while working in construction by learning how to draw again.",
    "I would soon find myself with even more time due to a circular saw accident. <br><br>Focusing on what I could do during my recovery, I started to remember all the other times when telling stories played a part in overcoming my adversities. Being in the right place at the right time, I was fortunate in being able to learn from others retelling times when they were tested both fictional and real. This served to normalize adversity as a part of improving as an individual. And that reminded me that with this newest challenge all I needed to do was take it on as a challenge and overcome the trial.<br><br>From feeling low and strung out for not having things go the way I planned it, to finding a strength waiting to be channeled into a direction I’ve wanted to go in for a long time – I finally made the decision to take on the challenge of combining the technical with the illustrative and try telling stories that can help others in a way that has helped me.",
    "With figuring out what I wanted to do with my ‘twinkle’, how I was going to do it was still up for debate. Settling on returning to school in earnest in 2021, I stumbled upon a saying: “A jack of all-trades is a master of none…”. Within each class I made it my mission to focus on project-based experience and use each assignment to test what a technical education could do with illustrative hobbies. And found myself comparing my abilities to that of my peers, coming to terms that I couldn’t be the best at everything.<br><br>But by knowing a little about a lot, I begun to understand the work needed to take ideas into final products. And started to practice the ability to start from crude thumbnails, plan out a workflow able to complete the job under the time constraint, and execute on the ideas. Leading to me stumble upon the entire saying: “A jack of all-trades is a master of none, But is sometimes better than a master of one.”<br><br>This gave me a new goal: Use this new experience in combining abilities and improve as many skills relevant to storytelling as possible. Even if I can’t be a master, by knowing as much as possible I can still make a difference by being able to foresee potential problems and mitigate their effects on the workflow needed to make a finished product.",
    "And with this story coming full circle, by the start of 2021 I found myself transitioning back into a position similar to how prepared I felt to take telling stories in 2015. I’m still unsure about how to go about getting the outcome that I want but am adamant about working towards it.<br><br>With a new plan in place via focusing on projects through a degree path to work on skills that can tell stories in different ways, the next course of action was to revisit the ideology behind why I wanted to do it. <br><br>One of the biggest benefits to stories is the ability to pass them off to the next generation. Being raised in by immigrant parents, a big theme in my life has centered around this idea of paying it forward to the next person. Looking into how someone’s life lessons has been used as support as I attempted to figure out how to make their lessons work for me just from hearing it. Developing my skills in design by combining Illustration, Scripting, and UX Design I want to be able to emulate what my parents and mentors have done for me and offer experiences that might one day become support for others."
]

