/*  Shining Drive JS

    Biography Page
    Goals:
        store the different stories within an array to be called later
    Author: Franco Ramos
    Date:   03/24/2023

    Filename: bio-stories.js
 */

let storyArray = [
    "Starting with my studies as an engineering technician in 2015, I would spend the time in between classes developing illustration skills – being smitten with the chance to one day work with storytelling as a concept artist, I would use all the time I could find to practice. <br><br>The degree was supposed to get me a job in a rookie position and make life become easier in terms of having the freedom to pursue what I really wanted with the financial support to make it happen. I graduated at the top of my class and couldn’t get anything. <br><br>This wasn’t the plan and I had to come up with something to do to support myself. So, I made the decision to transfer into studying to become an engineer as my illustrations weren’t anywhere near ready to go professional with. And in deciding to pursue something more realistic I made the difficult choice to put away all the progress I had made up to that point in illustration.",
    "Transitioning into mechanical engineering was its own type of challenge. In my extended family I’m in the first generation that has attempted to take on higher education and because of that had limited resources whenever there was an obstacle to overcome.<br><br>One of the greatest assets I did have was the chance to hang out in the parking lot after class and just share stories with my peers. Being in community college, there’s a fair number of circumstances that might lead someone to try and take on the challenge of trying to turn your life around with a degree, and through sharing we all got to peek a little into some of those circumstances and learn a little from those of us that gained a little wisdom from having more experience than others. <br><br>And while this helped in staying focused on what I was doing, I couldn’t help but think about what I wasn’t doing. The more I kept engineering as my end goal, the more I could see how some of the skills I was picking up through my program might help in picking up a forsaken dream. This is where I started my coding journey, got some jobs that taught me how to appreciate teaching a younger generation through robotics, and kept up some practice in 3D Modeling with Autodesk Inventor.",
    "Finding ways to expand my resources by sharing stories with Professors, they made it apparent that I might have a future in academics if I kept working towards it. But as the classes got harder, the motivation got weaker. My original goal was to prove to myself that I could manage an associate degree, which was proven back in 2018. The goal post then got moved to working towards a bachelor’s, with a possible master’s in the distance.<br><br>During 2020 in the last semester before I transferred into a bachelor’s degree program, I was able to attend a gathering for undergraduate students considering graduate work, I got to spend an entire day listening to other students who decided to put in 101% into their work and proved that they had a specific twinkle in their eye that let them put in that work. Meanwhile, as my reasons were beginning to reflect on what I could do for others – their origins have always been about the money. And after listening to other students pour their hearts out through their stories and how that motivated them to make change in the world, I spent the rest of my semester in shame and reflection.<br><br>The pandemic hit and I still didn’t have an answer to how to deal with my shame and thus stalled on bachelor’s program. And in figuring out how to navigate the world in its state of ‘new normal’ I got to spend some time thinking on the question of what to do about my ‘twinkle’ as I spent some time working in construction while sneaking away to work on my old drawings in my spare time.",
    "[Placeholder]",
    "[Placeholder]",
    "[Placeholder]"
]

