/*  Shining Drive JS

    Biography Page
    Goals:
        store the different stories within an array to be called later
    Author: Franco Ramos
    Date:   03/24/2023

    Filename: bio-stories.js
 */

let storyArray = [
    "Starting with the transition between high school and college in 2015, I had always been torn between deciding whether to commit to a hobby in illustration hoping it would someday turn into a career with no plan or sticking to the safe choice in mathematics and getting a stable job. Fearing the unknown, I began studying to become an engineering technician.<br><br>I would spend the time in between classes developing illustration skills – being smitten with the chance to one day work with storytelling as a concept artist, I would use all my free time to practice in secret. <br><br>The degree was originally supposed to get me a job in a rookie position and make life easier in terms of having the freedom to pursue what I really wanted with the financial support to make it happen. I graduated at the top of my class and couldn’t land any job because of a lack of experience. <br><br>This wasn’t the plan and I had to come up with something to do to support myself. So, I made the decision to transfer into studying to become an engineer as my illustrations weren’t anywhere near ready to go professional with. And in deciding to pursue something more realistic I made the difficult choice to put away all the progress I had made up to that point in illustration.",
    "Transitioning into mechanical engineering prove to also be difficult. In my extended family I’m in the first generation that has attempted to take on higher education and because of that had limited resources whenever there was an obstacle to overcome.<br><br>One of the greatest assets I found in pursuing engineering was the chance to hang out in the parking lot after class and share stories with my peers. Being in community college, there’s a fair number of circumstances that leads different people with different circumstances to take on the challenge of higher education. And we all got to peek into each other’s circumstances through our stories and learned a little from each other because of it.<br><br>And while this helped in staying focused on my goal of completing the program, I couldn’t help but think about what I wasn’t doing. The more I kept engineering as my goal, the more I could see how some of the skills I was picking up through my program might help in pursuing a forsaken dream. <br><br>This is where I started my story telling journey: I was lucky to coach young kids in Robotics and developed, and appreciation for passing down hard and soft skills because of it. And just like my time spent in the parking lot, started to think about what teaching through experience could look like as a career.",
    "Finding ways to expand my resources by sharing stories with Professors, it became apparent that I could have a future in academics if I kept working towards it. But as the classes got harder, my original motivation began hitting a limit. <br><br>When I started in higher education, I wanted to prove to myself that I could manage an associate degree, which was proven in 2018 with an AAS. The goal then transformed into working for a Bachelor’s degree with the option for a Master’s on the table. <br><br>Right before I transferred into a bachelor’s degree program, I was able to attend a gathering for undergraduate students considering graduate work. I got to spend an entire day listening to other students who found a way to put in 101% into their work and proved that they had a specific ‘twinkle’ in their eye that let them put in that work to help others with their research. <br><br>Meanwhile, I was having a hard time figuring out how to use my ‘twinkle’ to help others just like everyone I talked to that day. On that day, I could see how my ‘twinkle’ could get me this far in self-improvement but felt like it wouldn’t be enough to work on the same scale as the good people I met that day.  And after listening to them pour their hearts out through their stories and how that motivated them to make change in the world, I spent the rest of my semester in shame and reflection.<br><br>The pandemic hit and I still didn’t have an answer to how to deal with that shame and thus stalled on bachelor’s program, leaving my motivation at an all-time low. And while time in the world proverbially stood still, I got to spend the days thinking on what to do about my ‘twinkle’. Sneaking in time to do so while working in construction by learning how to draw again.",
    "I would soon find myself with even more time for reflection due to a circular saw accident. <br><br>Focusing on what I could do during my recovery, I started to remember all the other times when telling stories played a part in overcoming my adversities. Being in the right place at the right time, I was fortunate in being able to learn from others retelling times when they were tested in both fiction and non-fiction. This served to normalize adversity as a part of improving as an individual. And that reminded me that with this newest challenge all I needed to do was take it on as a challenge and overcome the trial.<br><br>From feeling low and strung out for not having things go the way I planned it, to finding a strength waiting to be channeled into a direction I’ve wanted to go in for a long time – I finally made the decision to take on the challenge of combining the technical with the illustrative and try telling stories that can help others in a way that has helped me.",
    "Figuring out what my ‘twinkle’ could transform to take on this new challenge, how I was going to do it was still up for debate. Settling on returning to school in late 2021, I stumbled upon a saying: “A jack of all-trades is a master of none…” during project on Pablo Ferro. Within each class I made it my mission to focus my assignments on testing what my technical studies could do combined with my illustrative hobby. But found time being my strongest constraint since I kept trying to take every aspect on a project and develop them as far as possible before the deadline.<br><br>This created a scenario where I spent time on every project thinking about the work needed to take ideas into their final products. And started to practice skills from factory production into these projects of traditional art: starting from crude thumbnails, plan out a workflow able to complete the job under the time constraint, and execute on the ideas for an audience to view. Leading to me stumble upon the entire saying: “A jack of all-trades is a master of none, But is sometimes better than a master of one.” <br><br>This gave me a new goal: Use this new perspective in combining abilities and improve as many skills relevant to storytelling as possible. Even if I can’t be a master, by knowing as much as possible I can still make a difference by being able to foresee potential problems and mitigate their effects on the workflow needed to make a finished product.",
    "And with this story coming full circle, by the start of 2022 I found myself fearing the unknown again, but this time the goal needs me to embrace both the technical and artistic to tell stories that help people deal with their challenges and supports them in a way that helped me when I needed it. <br><br>And with this new goal in place, the plan became to continue working on projects that focused on silent storytelling. I don’t know if I could’ve appreciated all the lessons I learned if they were spelled out for me. And in retrospect, think that the challenge was a key factor in my skills and ‘twinkle’ developing as far as they have since diamonds are made under pressure.<br><br>One of the biggest benefits to stories is the ability to pass them off to the next generation. Being raised in by immigrant parents, a big theme in my life has centered around this idea of paying it forward to the next person. And by listening to how someone else’s life lessons have been developed, I could use it as support as I attempted to figure out my own way. By developing my skills in storytelling, I want to be able to emulate what my parents and mentors have done for me and offer experiences that might one day become support for others."
]

